name: supernote
description: "A OneNote clone"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  darkstorm_common: ^2.0.1
  styled_text: ^8.1.0
  two_dimensional_scrollables: ^0.3.2
  single_child_two_dimensional_scroll_view: ^0.0.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
